name: coocree_youtube_web
description: Esta é uma implementação do plug-in webview_flutter para web que é adaptado para uso com o pacote youtube_player_iframe, ela é uma versão levemente adaptada da biblioteca https://github.com/sarbagyastha/youtube_player_flutter/tree/master/packages/youtube_player_iframe_web
version: 1.0.0
homepage: https://github.com/coocree/coocree_youtube_web

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

flutter:
  plugin:
    implements: youtube_player_iframe
    platforms:
      web:
        pluginClass: WebYoutubePlayerIframePlatform
        fileName: src/web_youtube_player_iframe_platform.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  webview_flutter_platform_interface: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
